name: master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET Core 3.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x             
      - name: Build
        run: dotnet build src/DiagnosticContext.sln --configuration Release
      - name: Pack
        run: dotnet pack src/DiagnosticContext.sln -c Release -p:BuildNumber=${{ github.run_number }}
      - name: Publish
        run: dotnet nuget push **/*.nupkg -k ${{secrets.MINDBOX_PRIVATE_NUGET_AUTH_TOKEN}} -s https://mindbox.myget.org/F/mindbox-private/api/v3/index.json
