name: Pull request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check License Lines
        uses: kt3k/license_checker@v1.0.6     
      - name: Build & Test
        run: dotnet test src/DiagnosticContext.sln --configuration Release